### ISSUE TITLE
Getting Data out of Target Runner

### ISSUE THREAD

**Issue by DE0CH** [auto-optimization/iracepy#13]
Because of some multiprocessing nonsense, nothing can get out of the target runner. It can't write to any variable outside the function. There are two solutions for this. 

1. Ignore it. If users want to get data out, they can figure out a hacky way to do it themselves like writing to disk, printing to stdout or send data through a TCP / unix socket. 
1. Find a way to allow user to pass some shared memory into target runner, such as `multiprocessing.Queue`. Preliminary, I think this can be done by writing a `targetRunnerParllel` in a way that makes sure shared memory objects can get through and irace doesn't try to spawn new processes. 

What do you think, Manuel? Since I presume the use case is quite narrow, I'm in favour of the first option to spare me some work.

**Comment by MLopez-Ibanez** [comment]
Users can use `multiprocessing.Queue` or some other way to communicate between processes, why this doesn't work? What are you trying to do?

**Comment by MLopez-Ibanez** [comment]
But I guess the best option is highly application-dependent: some users would prefer to use files, others would prefer TCP/unix sockets and others would prefer shared memory. There is no one solution that works for everyone and I don't see any solution more hackish that another. Hackish would be to reimplement what `multiprocessing.Queue` already does.

**Comment by DE0CH** [comment]
> Users can use multiprocessing.Queue or some other way to communicate between processes, why this doesn't work? What are you trying to do? 

I tried. I don't think it works, unless I did something wrong. I'm guessing when irace forks processes, it serialises all the data and then recontruct them on the other end. When I tried to pass an `multiprocessing.Event`, I got a traceback pointing to some pickling code.

**Comment by MLopez-Ibanez** [comment]
A traceback from R? or from Python?  But still, what are you trying to do/share between processes?

**Comment by DE0CH** [comment]
Sorry I must have gotten something terribly wrong previously. I just tried to create an example and it worked.
