### ISSUE TITLE
digits should not be set to 4 always

### ISSUE THREAD

**Issue by MLopez-Ibanez** [auto-optimization/iracepy#14]
https://github.com/auto-optimization/iracepy/commit/c57fe3090ee7b1a37104dd88c101cee99224ed43#r91074601

Also, that test is not very useful because such a thing should be tested in irace (it is already tested there). 
iracepy should avoid redoing the work that is already done in irace. Otherwise, you (we) are wasting our time instead of actually doing novel things.

**Comment by DE0CH** [comment]
It doesn't really test irace. It tests that if the user does not specify a default value, it won't just throw a `KeyError`
