### ISSUE TITLE
NA integer gets converted to -2^31 by rpy2

### ISSUE THREAD

**Issue by DE0CH** [auto-optimization/iracepy#19]
It seems that NA for any integer gets converted to -2^31 by `rpy2`. You can see this by running the `test` function in `tests/test_data_conversion.py`. The bug doesn't seem to come from `iracepy` because the number is `-2^31` even before the line `res.applymap(r_to_python)` is called. 

A few ways to deal with this bug:
1. Convert `-2^31` to `np.nan`. This should work most of the time because it's quite unlikely that a number is exactly tuned to `-2^31`. 
2. Write the conversion from r list to `pd.DataFrame` ourselves from scratch. 
3. Investigate the bug in `rpy2` and open an issue / PR.

What do you think, Manuel?

Part of the print for the run:
```
Description of the best-so-far configuration:
  .ID. one  two three four .PARENT.
1    1 '1' <NA>    NA   NA       NA

# 2022-12-02 16:32:44 UTC: Elite configurations (first number is the configuration ID; listed from best to worst according to the sum of ranks):
  one  two three four
1 '1' <NA>    NA   NA
3 '0' <NA>    NA   NA
# 2022-12-02 16:32:44 UTC: Stopped because there is not enough budget left to race more than the minimum (4)
# You may either increase the budget or set 'minNbSurvival' to a lower value
# Iteration: 5
# nbIterations: 5
# experimentsUsedSoFar: 175
# timeUsed: 0
# remainingBudget: 5
# currentBudget: 5
# number of elites: 2
# nbConfigurations: 2
# Total CPU user time: 1.142, CPU sys time: 0.006, Wall-clock time: 1.147
   one   two  three        four
1  '1'  None    NaN -2147483648
3  '0'  None    NaN -2147483648
R[write to console]: There were 25 warnings (use warnings() to see them)
R[write to console]: 
```

**Comment by MLopez-Ibanez** [comment]
Probably `rpy2` has decided to leave this to users to handle in whatever way they believe is more correct.

I think the right answer would be to write our own conversion functions:  https://stackoverflow.com/questions/72657405/rpy2-r-python-data-frame-bad-na-and-custom-converter

The whole `r_to_python` function could go away and become a set of conversion functions.
