### ISSUE TITLE
Rename the package to iracepy

### ISSUE THREAD

**Issue by DE0CH** [auto-optimization/iracepy#20]
It might be a bit confusing if the package in python does not have the same name as that on PyPI, so I think it might be better to rename the package to `iracepy` to avoid confusion.

**Comment by MLopez-Ibanez** [comment]
Where in PyPI does it say that the name of the package is `iracepy`? Sorry I don't understand what you mean.

**Comment by DE0CH** [comment]
I'm sorry I got it confused. Only the repo name is named `iracepy`. It will be `irace` when we push to PyPI.
