### ISSUE TITLE
Embedded R runs interactively causing program to get suck on error

### ISSUE THREAD

**Issue by DE0CH** [auto-optimization/iracepy#21]
In `rpy2`, the embedded `R` is set to run interactively, meaning `irace` will use `recover` on error which waits for an input for humans to inspect the stack frames instead of printing out the trackback and exiting. This means if the user's program crashes, it gets stuck instead of exiting. Even automated tests get stuck instead of failing. In the next commit (f71e759), I will implement a workaround to initialise embedded r with `interactive` set to false using `rpy2.rinterface.embedded._initr`. 

The `rpy2`'s decision to initialise r with interactive set to `True` instead of `False` is quite baffling to me. At least it would detect if there's an pseudotty or if python is being run inside a Jupyter notebook. In any case, I think setting interactive to False by default is a safer option anyways. 

There is also no documented function to set that option. The documented `rpy2.rinterface.initr` has no way to set the option. As indicated by the leading underscore `embeded._initr` is probabaly intended to be used internally and its signature might change between minor version bumps so relying on it is probabaly not a good idea. 

Few solutions:
1. Open a issue / PR in `rpy2` to address this issue
2. Add an way in `irace` to override the change in behaviour such as `option(error=TRUE)` if `interactive()`.

**Comment by MLopez-Ibanez** [comment]
>     2. Add an way in `irace` to override the change in behaviour such as `option(error=TRUE)` if `interactive()`.

I think we should keep running with interactive to avoid bug #27 , and change irace to not use `recover()`.

**Comment by MLopez-Ibanez** [comment]
>     2. Add an way in `irace` to override the change in behaviour such as `option(error=TRUE)` if `interactive()`.

I think we should keep running with interactive to avoid bug #27. I changed irace to not use `recover()`.
