### ISSUE TITLE
pytest in test-dev started failing without a clear reason

### ISSUE THREAD

**Issue by MLopez-Ibanez** [auto-optimization/iracepy#24]
It just says `Error: Process completed with exit code 2.`

See: https://github.com/auto-optimization/iracepy/actions/runs/3716899297/jobs/6303741474

**Comment by DE0CH** [comment]
I feel like the dev branch is more or less unnecessary. It's one more branch to maintain and a source of merge conflict. I think the better way is to just keep the PR unmerged until a new version of irace is published on CRAN.

**Comment by DE0CH** [comment]
Seems like there is a bug in the devel version of r. See https://github.com/auto-optimization/iracepy/actions/runs/3721555051/jobs/6311786532. Every devel version failed, but release version did not. I think we should just turn off testing against devel version.

**Comment by MLopez-Ibanez** [comment]
Ok, I saw your changes but if we are going to test it in this way, can we
just test python 3.6 as the minimum supported version and python
latest version? Testing all intermediate versions makes the testing matrix
way too large and a waste of resources. If something works in python 3.6
and in the latest python, the probability that it doesn't work in some
intermediate version is very small. I rather have more tests and more
complicated than test so many versions or python.

**Comment by DE0CH** [comment]
I also added a matrix for upgrading or not upgrading the pip packages.

Can we close this issue now?
