### ISSUE TITLE
Exiting R exits python

### ISSUE THREAD

**Issue by DE0CH** [auto-optimization/iracepy#27]
When irace has an internal error, it calls `q` which exits R. But when R is used in python, this also takes down the entire python interpreter with it. This means this exception cannot be caught. This also makes pytest exit without printing out the report of the error. 

For example, the program would just exit at `f()` without raising an exeception.

```
from rpy2.robjects import r

f = r('f <- function() {q("no", status = 1, runLast = FALSE)}')
try:
    f()
except:
    # this hi never gets printed.
    print("hi")
```

However, using the `stop` function in r would cause `rpy2` to raise an exception that can then caught by calling functions. Is there any way to make R CMD check work with `stop`? 

As a workaround, though, we can call irace in a `multiprocessing.Process` which we could then check if it crashed or not by reading a flag it would set when it exits correctly.

**Comment by MLopez-Ibanez** [comment]
> When irace has an internal error, it calls `q` which exits R. 

Where do you see this? I cannot see anywhere `irace` calling q().

**Comment by DE0CH** [comment]
In line 77 of function `irace.dump.frames` in `utils.R`, which is used in `irace.internal.error`.

**Comment by MLopez-Ibanez** [comment]
True, I wonder if that is still necessary. Using q() in that way doesn't
seem right. Maybe raising another error would be enough.

**Comment by MLopez-Ibanez** [comment]
> True, I wonder if that is still necessary. Using q() in that way doesn't seem right. Maybe raising another error would be enough.

It seems to be necessary still for non-interactive sessions. So the only option is to run irace interactively in rpy2, which anyway is the default.

**Comment by MLopez-Ibanez** [comment]
Can we close this now? `q()` is only called for non-interactive sessions so it should not be a problem now.
