### ISSUE TITLE
Problem reading instances

### ISSUE THREAD

**Issue by scaverod** [auto-optimization/iracepy#4]
**Purpose**: provide to irace a path to the folder where instances are located. 

**What am I doing?**
First I configured the scenario as follows: 
```
path = "path_to_folder"
scenario = dict(instances=path, maxExperiments=1000,    digits=2,    parallel=1, logFile="")
```

When executing the target runner I printed out the experiment configuration:
`OrderedDict([('id.configuration', 1.0), ('id.instance', 1), ('seed', 614913377), ('configuration', OrderedDict([all_configuration)])), ('instance', 'path_to_folder'), ('bound', None), ('switches', [....])])`

As can be seen (value of attribute `instance`), the experiment recieves the path of all instances, not a single instance. 

**What did I  also try?**
```
path = "path_to_folder"
list_of_paths_to_instances = // get the path of all instances in the folder
scenario = dict(instances=list_of_paths_to_instances , maxExperiments=1000,    digits=2,    parallel=1, logFile="")
```

Then, I had the following error: 
`<class 'TypeError'>: 'NULLType' object is not iterable`
```
....
  File "/home/sergiocavero/.local/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/home/sergiocavero/.local/lib/python3.8/site-packages/rpy2/rinterface.py", line 680, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error: == irace == The output of targetRunner must be a list
== irace == The output was:
```

Therefore, how should you indicate in the scenario the instances to be considered?

**Comment by MLopez-Ibanez** [comment]
The first option does not work. You need to use trainInstancesDir=path so that irace will populate "instances" itself.

The second option should work but there may be a problem in how you save the list in "instances" or, more probably, in how your targetRunner uses those instances. Is there any way you can make your code available? It is difficult to understand what is going on without more details.

**Comment by scaverod** [comment]
Using trainInstancesDir=path works.
