### ISSUE TITLE
Setup CI (github actions)

### ISSUE THREAD

**Issue by MLopez-Ibanez** [auto-optimization/iracepy#8]
We should setup GitHub Actions to build the package and run a testsuite.

See examples here: https://github.com/poliastro/poliastro/tree/main/.github/workflows
and here: https://github.com/anyoptimization/pymoo/tree/main/.github/workflows

**Comment by DE0CH** [comment]
Completed via [d94a5d6](https://github.com/auto-optimization/iracepy/commit/d94a5d641f6994a37e51e68d9599c34786d22ade).

**Comment by MLopez-Ibanez** [comment]
Thanks! Is it running? I cannot see any runs in recent commits.

**Comment by DE0CH** [comment]
It was not because ghcr.io was having some issues. It is now, but the `test-dev` which installs irace from github is not working because I can't figure out how to install devtools. I am still trying to fix it now.
